name: Test Util
on:
  workflow_dispatch: # manually triggered

  pull_request:
    branches:
      - master

  schedule:
    - cron: '45 9 * * *' # daily at 9:45 UTC (11:45 EEST)

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # print useful informtion
      - run: lsb_release -d
      - run: pwd
      - run: ls
      - run: node -v
      - run: npm -v

      - name: Install dependencies
        run: npm install

      - name: Unit test
        run: npm test
